name: "Build and Deploy Angular app to Github pages"

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Set up Node.js"
        uses: actions/setup-node@v1
        with:
          node-version: "v16.17.1"

      - name: Install Dependencies
        working-directory: ./hello-world
        run: npm ci

      - name: Build
        working-directory: ./hello-world
        run: npm run build

      - name: Test
        working-directory: ./hello-world
        run: npm run test -- --watch=false --browsers=ChromeHeadless

      - name: Archive build
        uses: actions/upload-artifact@v1
        with:
          name: deploy_dist
          path: dist

      - name: Archive code coverage result
        uses: actions/upload-artifact@v1
        with:
          name: deploy_coverage
          path: coverage

      - name: Checkout
        uses: actions/checkout@v1

      - name: Download build
        uses: actions/download-artifact@v1
        with:
          name: deploy_dist

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB_ACTION }}
          BRANCH: gh-pages
          FOLDER: deploy_dist/angular-demo
